### ISSUE TITLE
Daikin AI - fan support

### ISSUE THREAD

**Issue by terjecorneliussen** [robertklep/name.klep.homekitty#27]
### Type (brand/model) of device
Daikin AI v5.2.1
...

### Is it supported by HomeyKit?
Yes - sort of

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: thermostat
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

*thermostat_mode_std - Operation Mode - enum
*fan_rate - Fan speed - enum
*fan_direction - Airflow direction - enum
*special_mode_eco - Econo - enum
*special_mode_pwr - Powerful - enum
*special_mode_str - Streamer - enum
*target_humidity - Target humidity - number
*target_temperature - Target temperature - number
*measure_temperature - Temperaturenumbere - number
*measure_temperature.inside - Inside - number
*measure_temperature.outside - Outside - number

The thermostat is already supported. But I think it would be great if it would support the fan speed too. The fandirection is not that important but if you have a great idea how to implement it I would not be mad…
Home assistant is solving this with pairing a fan with the thermostat. Works great…

**Comment by OlivierZal** [comment]
@terjecorneliussen, problem is that Homey has no standard capabilities for fan speed and vane directions.

**Comment by terjecorneliussen** [comment]
Do you have any idea how to achieve controlling the fan? Maybe a button for “quiet mode”?

It that the same reason there is no support for a vacuum cleaner? Home assistant is also using fan speed…

**Comment by robertklep** [comment]
Homey has a "fan" device but not a capability for its speed. Some implementation use the `dim` capability for speed, which translates nicely to how the HomeKit protocol defines the rotation speed of a fan (as a percentage of its maximum speed), so that's the only configuration that HomeKitty currently supports.

The Daikin app instead defines [a custom capability `fan_rate`](https://github.com/PeterEIER/nl.climate.daikin/blob/5624f57d37c39c2510bd930c1ac3fed97ad505b3/app.json#L2097), but even if I were to consider implementing support for it, I have no idea what its values ("Level 1", "Level 2", etc) actually mean.

Which is the problem with custom capabilities: they typically only make sense within the context of the app that defines them (not to mention that if another app comes along that would also define a custom `fan_rate` capability but based on RPM, HomeKitty couldn't support that without a lot of special case handling).

Perhaps you can ask the Daikin app developer to support the `dim` capability too.
