### ISSUE TITLE
Device disappear

### ISSUE THREAD

**Issue by Fryar27** [robertklep/name.klep.homekitty#30]
Hello Robert and again thanks a lot for this app ! 

I've setup successfully your app and done the migration from the previous one. 
All is working perfectly and gain some functionality.

However i'm encouterring an issue with 2 devices : 
- 1 light
- 1 covering window

One light keep disappearing from Homekit every day, i must go to HomeKitty and disable/enable the light and the light reappear in the "Default Room" in Home. 
The covering just switch to the "Default room" and no staying in the "Kitchen" Room.

I've tried to rename the light without accent or special caracter in the name without success.

All my light are Philips hue and and all covering are Fibaro Walli roller shutter. I don't understand why this two get this behavior.
If you have any idea ... 
Regards,

Julien / Fryar

**Comment by robertklep** [comment]
Very strange, especially if you have multiple devices of the same brand/model for which it works fine. I assume that the devices work fine in Homey?

Are you using the new Home architecture that was introduced with iOS 16.2 (you would have gotten a question if you wanted to upgrade)? If so, it might be related to that because Apple has since retracted the option to upgrade because the new architecture had so much issues.

**Comment by Fryar27** [comment]
Yes strange issue. All device work fine with Homey. 
Yes i've upgrade to the new home architecture after you made the necessary update on the previous app so before switch to HomeKitty.
I've aware that apple retracted the upgrade ! 
I've also tried to remove some devices i don't need on the Home interface. i will continue my troubleshoot and keep you inform.

**Comment by Fryar27** [comment]
Hello there,

So i finally figure out what was the problem.
For several reason i've schedule a restart of some apps every night on my Homey.
I have disable the reboot for the Philips and Fibaro Apps and since 48 hours all seems stable :)
