### ISSUE TITLE
[Valve]

### ISSUE THREAD

**Issue by massari46** [robertklep/name.klep.homekitty#55]
(make sure you also edit the title)

### Type (Tuya Smart water valve / _TZ3000_iedbgyxt) of device
...

### Homey Model
- [ ] "old" Homey (Pro)
- [X] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [x] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: other
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* ...Turn on / turn off
* ...
* ...

**Comment by robertklep** [comment]
If the device has class "other" and only the "onoff" capability, HomeKitty has no idea that it's a valve, and cannot present it as such to HomeKit. It can only present it as a switch.

**Comment by massari46** [comment]
I understant. Is it possible to change the device type or add an option to "show as" in the HomeKitty settings?

**Comment by robertklep** [comment]
Changing the device class isn't possible (and besides that, Homey doesn't have a "valve" device class), implementing something like "show as" is technically possible, but won't solve your problems.

In HomeKit, a valve has three _required_ characteristics/capabilities: "Active", "InUse" and "ValveType" ("Generic", "Irrigation", "Shower Head" and "Water Faucet").

All of these are not provided by Homey, so that problem should be solved too and would require an elaborate "device builder" in HomeKitty. Not something I'm planning to implement, I'm afraid 🥴
